### PR TITLE
Add Russian and Ukrainian translation (partly) 

### PR DESCRIPTION
**Pull request by bac1**

### CODE REVIEW

**Comment by tibbi** [comment]
hm, why have you translated some strings only?

**Comment by bac1** [comment]
@tibbi I am unable to translate everything partly because of misunderstanding, partly because of laziness. And sometimes one word, for example dialpad, translates into three or four words.

**Comment by bac1** [comment]
@tibbi Sometimes I get confused because two words are translated the same way. For example dialer and caller translate as "абонент". And because of my not very good English, I cant understand if there is a difference between them. dialer - any interlocutor? caller - the interlocutor who started the call? Or is there no difference?

**Comment by bac1** [comment]
@tibbi Sometimes it is possible to translate, but due to lack of context I do not understand exactly how

**Comment by tibbi** [comment]
dialer is the app name, caller is the person who is calling. Thanks anyway

**Pull request merged**
