### PR TITLE
Minor call UI improvements

### PR DESCRIPTION
**Pull request by Naveen3Singh**

### CODE REVIEW

**Comment by tibbi** [comment]
the color changing animation looks a bit weird, maybe the color animation and ripple are mixing up?

**Comment by tibbi** [comment]
maybe this a good chance to rewrite the dialpad too onto a bottom sheet

**Comment by Naveen3Singh** [comment]
Actually, that GIF is not rendered properly, it looks like this:
https://user-images.githubusercontent.com/36371707/200602692-e561e1e0-26ce-412b-855c-1220e689eab1.mp4

**Comment by Naveen3Singh** [comment]
> maybe this a good chance to rewrite the in-call dialpad too into a bottom sheet

Usually, bottom sheets have a [much higher elevation](https://m2.material.io/components/sheets-bottom) than what would look okay for a dialpad. Why not just elevate the existing dialpad view with animated translationY?

**Comment by tibbi** [comment]
I tried the animation in the app itself, wasnt just viewing the gif. Lets skip the bottom sheet then for now.

**Comment by Naveen3Singh** [comment]
> Lets skip the bottom sheet then for now.

that is, leave dialpad as it is yeah?

**Comment by tibbi** [comment]
> > Lets skip the bottom sheet then for now.
> 
> that is, leave dialpad as it is yeah?

well, lets ignore it for now, but it would be good to make it somehow nicer eventually

**Comment by tibbi** [comment]
that light primary color looks strange, lets just use grey shades there

**Comment by Naveen3Singh** [comment]
done :+1:

**Comment by tibbi** [comment]
yeah, lets elevate it

**Comment by tibbi** [comment]
ye looks good, thanks

**Pull request merged**
