### PR TITLE
FR #200 Remove dialer from recent apps after hanging up a call

### PR DESCRIPTION
**Pull request by p0ppy-fl0w3r**
- Changed menifest.xml and CallActivity.kt and now the app is excluded from 'recent app list' when the user hangs up the call.
- Also fixed a string in Italian translation that was preventing the app from being built.

### CODE REVIEW

**Comment by tibbi** [comment]
Thanks, but remove all those unnecessary code style updates unrelated to the issue please.

**Comment by p0ppy-fl0w3r** [comment]
I'm extremely sorry about that. I did not realize I pressed the format shortcut.

**Comment by p0ppy-fl0w3r** [comment]
I'm extremely sorry about that. I did not realize that I pressed the format shortcut.

**Comment by tibbi** [comment]
should be good, thanks :) closes #200

**Pull request merged**
