### PR TITLE
ability to test manage blocked numbers

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by tibbi** [comment]
1. top bars are too light after long pressing an item
2. add spaces at selected item counter at the top left corner, should be "1 / 2" instead of "1/2"
3. clicking on the selected item counter should trigger Select all, then Deselect all
4. text size of menu items Copy number to clipboard and Delete are too small
5. long pressing the top menu buttons both in casual menu and contextual should vibrate and show a label of the menu button
6. selected items in light mode and ripple cannot be seen at all
7. with light mode the top status bar isnt visible at all, top icons, clock, battery etc should use dark colors
8. checkbox and 3 dots colors dont change properley

**Comment by tibbi** [comment]
9. clicking on 3 dots, the floating ones on the right side should have circle ripple, not square

**Comment by FunkyMuse** [comment]
managed to fix everything except: long pressing the top menu buttons both in casual menu and contextual should vibrate and show a label of the menu button

I think Compose doesn't bring this out of the box, will look for a flexible solution

**Comment by tibbi** [comment]
1. in dark Material You theme, the top bars are still way too light, cant we use something like on the main app screen?
2. with Material You theme the marked selected item should be a bit colored, not just grey
3. in Light theme after long pressing an item the top bars should be dark, not primary color. And no matter what colors are the top bars, the top system bar and our menu should use the same colors, either light or dark.
4. when selection mode is active, pressing Back should just deselect everything, not close the screen
5. floating menu text sizes are ok, but lets add a bit more vertical spacing
6. 3 dots and inactive checkboxes should use the text color
7. sometimes after I long press an item and lift by finger up, it gets deselected

**Pull request closed without merging**
