### PR TITLE
Show only the needed floating menu action buttons

### PR DESCRIPTION
**Pull request by pavelpoley**
Show only the needed floating menu action buttons

### CODE REVIEW

**Comment by tibbi** [comment]
lets also show cab_call_sim_1/2 and remove_default_sim, whenever it is shown at the top menu after long pressing 1 item

**Comment by tibbi** [comment]
lets add cab_remove_default_sim too

**Comment by pavelpoley** [comment]
"lets also show cab_call_sim_1/2" - cab_call_sim_1/2 should be there as icons in toolbar, maybe you mean to add "call" for a single sim?

**Comment by tibbi** [comment]
I deleted that message, those items are there already. But the remove_default_sim likely isnt

**Pull request merged**
