### PR TITLE
Show incoming calls as a notification

### LINKED ISSUE #315: Feature Request: An option for dialer to not bring itself to foreground when the device is being used
When the user is doing something on his device, he may opt to be interrupted more gently - through system notifications, which the user can then set up to pop on the screen for better UX.

True Phone does the same, although it builds on the Picture in Picture permission rather than notifications.

### PR DESCRIPTION
**Pull request by sdex**
Show a high priority notification when a device is in an interactive state

closes #315

image

### CODE REVIEW

**Comment by tibbi** [comment]
looks good to me, thanks

**Comment by sdex** [comment]
In this case, I suppose I have to check both states. `STATE_DIALING` didn't work for me when I was testing it.

**Comment by Yann-Kaelig** [comment]
Hello

Thx for all of these great softwares.
How can i get back the previous behavior when the call entry notification was at the bottom. My mom is an elderly person who needs big colored text, icons and slide to reply. She is telling me that now the test is too small with very poor clarity, the window notification disappears way too fast , there is no slide anymore which is less important.

**Comment by tibbi** [comment]
You can find all app versions at https://github.com/SimpleMobileTools/Simple-Dialer/releases

**Pull request merged**
