### PR TITLE
Added hiding tabs (#183)

### PR DESCRIPTION
**Pull request by Aga-C**
Hi,

I've added an option to hide Contacts and/or Favorites tab. It works similarly to Contacts app, despite the fact, that here I'm always enforcing History tab to not be hidden. I decided to do this because it's the tab to which we're brought from missed call notification; I didn't want to break this functionality. 
Additionally, while doing this I've found out, that if the default tab was set to recently used, it wasn't always remembering it. That was a simple fix to do because saving was done in a wrong place.

https://user-images.githubusercontent.com/85929121/136651401-0425c59d-2501-4de6-b53a-7d8c873bed97.mp4

### CODE REVIEW

**Comment by tibbi** [comment]
reuse the way it is done in Simple Contacts or other app for consistency, avoid creating a new solution please

**Comment by Aga-C** [comment]
It is the same solution as in Contacts. I've just reworked the conditions, because there were bugs related to the last card (the bug is also present in Contacts and I can solve it later).

**Comment by tibbi** [comment]
not really, it is not the same. This app has some delay before actually marking the selected tab that makes it look quite glitchy

**Comment by Aga-C** [comment]
Ok, I will take a look later today.

**Comment by Aga-C** [comment]
What kind of glitches and delay you mean? I've tested on emulator and device and haven't experienced any in compare to current app version. If there's a particular one I can reproduce, I can try to fix it.

About differences in code - I've checked the code once again, and in fact, in MainActivity it's done differently than in Simple Contacts. But the reason was very simple - MainActivity in terms of handling view pager is written different in both apps. When I've done it exactly the same way as in Simple Contacts, I've encountered too many strange problems (tabs weren't hiding after returning from settings, tabs were having wrong contents, search was losing text, and some other bugs) that would probably require rewriting a lot of other code related to ViewPager, that's why I've remade it this way.

**Comment by tibbi** [comment]
Coloring the initially selected tab has a tiny delay in your implementation. And there is no hideTabs() function in our other apps.

**Comment by Aga-C** [comment]
I don't have any delay with coloring initially selected tab, neither on emulator nor on a device. About hideTabs(), that's exactly what I wrote in a comment before. I couldn't do the same logic in initFragments() as there's in Simple Contacts (or Simple File Manager), because it was generating too many problems due to different implementation of setting view pager in both apps. That's why I did hideTabs function with a bit of different logic, executed in another place.

**Comment by tibbi** [comment]
2 notes. 1. avoid refreshing the lists on every resume, the animation is annoying. 2. if only 1 tab is shown, hide the top tab holder

**Comment by Aga-C** [comment]
I couldn't reproduce any animation on onResume (I also haven't done a refresh here) so I hope it works correctly now after my fix. I've also added hiding tab holder.

**Comment by tibbi** [comment]
nope, it is still refreshing on every resume. Used to work well

**Comment by Aga-C** [comment]
I've done another fix for it. I still couldn't reproduce it, so I hope this one will work. If this doesn't work, I have no idea what else could be done here.

**Comment by tibbi** [comment]
there is no refreshing now, but if you change the shown tabs, it is empty and not populated on resume

**Comment by Aga-C** [comment]
I see that merging the latest master has broken the app. Probably some change in Commons is breaking the tab hiding. I'm investigating it.

**Comment by tibbi** [comment]
nothing really related should have changed, Im intentionally not commiting along those lines anything now

**Comment by Aga-C** [comment]
From what I see, this change has somehow broken viewpager, that it doesn't show fragment contents after changing tab visibility: <https://github.com/SimpleMobileTools/Simple-Commons/commit/51f1996098dc809b63de95f954fb9678db405ae8>. I've tried to fix it, but I don't see any solution right now. Maybe you have any idea, how changing fastscroller could break it?

**Comment by tibbi** [comment]
not really, that definitely didnt break it. The dialer doesnt even use the new fastscroller, it uses the other one with letters.

**Comment by Aga-C** [comment]
I've checked and in fact it hasn't changed anything. I've dug a bit more and found out that it broke after upgrading Kotlin to the newest version. I've reverted it back to 1.5.31, and it works again. Have you checked if upgrading Kotlin version doesn't break anything in other apps? Because I don't know if it's something with my code or with Commons.

**Comment by tibbi** [comment]
ah, that is so messed up that updating kotlin can break anything. I haven't noticed issues with other apps, but I haven't been updating kotlin much yet. Will keep an eye on it, thanks

**Pull request merged**
