### PR TITLE
Added swipe to answer an incoming call (#127)

### LINKED ISSUE #127: Swipe to Answer
I think u want to change call screen UI. Because Now (call screen ui) is accidental touch to answer or reject the call. Pls change swipe to answer call UI so, we can reduce accidental touch to answer or reject the call. so, pls consider this issue to create UI change in SIMPLE DIALER 6.0👍

IMG_20201210_100653_229

### PR DESCRIPTION
**Pull request by Aga-C**
Hi,

I've added an optional swipe to answer a call. It's done in a similar way as in Simple Clock. Closes #127

https://user-images.githubusercontent.com/85929121/144223589-0bcae46b-7cbb-49d4-8342-f56415616201.mp4

### CODE REVIEW

**Comment by tibbi** [comment]
it needs some hint to be shown that the user is supposed to drag the icon to one side, it isnt really clear

**Comment by Aga-C** [comment]
I thought about it, but I don't know what would be the best approach. In Simple Clock there are no labels under icons and hint appears after unsuccessful swipe. Here swiping is not active by default, user has to turn it on in Settings, so he should know how to operate it, especially that there are still original labels that tell where to swipe to do which action.

Maybe just a simple text "Swipe receiver icon to choose an action" under the swipeable icon?

**Comment by tibbi** [comment]
nah, showing texts at such screens is terrible UX. Add either some moving circles from the middle button to the sides, or arrows like at https://dribbble.com/shots/4870276-Incoming-call-made-with-framer

**Comment by Aga-C** [comment]
I've done it in a simple way:

https://user-images.githubusercontent.com/85929121/144291925-0a0db2d1-aa8e-448e-8866-b16b736cd10b.mp4

**Comment by tibbi** [comment]
color the arrows too please

**Comment by tibbi** [comment]
lets actually remove the setting and make it the only option for now, will add it back if too many people want to disable it

**Comment by Aga-C** [comment]
Done.

https://user-images.githubusercontent.com/85929121/145727628-5d1bc50c-803e-4a14-aca5-8b40348523ad.mp4

**Comment by tibbi** [comment]
if you drag it to the right side and keep dragging over the green area without releasing your finger, it keeps vibrating on every move. You should stop the move handing once it reaches either accept or decline

**Comment by Aga-C** [comment]
I think it should be fixed now.

**Comment by tibbi** [comment]
should be good now, thanks

**Comment by tibbi** [comment]
yeah, so can you add that setting for toggling gestures? Many people are asking for it as kind of expected. Make it something like "Replace swiping at responding to incoming calls with clicking" and disable it by default. Im not sure how could we explain it with a shorter string. Thanks

**Comment by Aga-C** [comment]
Ok, no problem.

**Pull request merged**
